#pragma once
#include"ActionDDOOC.h"
#include"ActionCourseDependancies.h"
#include"ActionAddCourse.h"
#include"ActionSavePlan.h"
#include"ActionDeleteCourse.h"
#include"ActionAddNotes.h"
#include"ActionImportPlan.h"
#include"ActionEraseAll.h"
#include"ActionMoveCourse.h"
#include"ActionCourseInfo.h"
#include"ActionChangeCode.h"
#include"ActionDragAndDrop.h"
#include"ActionDeclareMajor.h"
#include"ActionCalculateGPA.h"